workflows:
  flutter-workflow:
    name: HS Logistics Build
    max_build_duration: 60
    instance_type: mac_mini_m2

    scripts:
      - name: Check Flutter version
        script: flutter --version

      - name: Install dependencies
        script: flutter pub get

      - name: Ensure android and ios folders exist (but don't overwrite lib/)
        script: |
          if [ ! -d "android" ]; then
            flutter create .
            rm -rf lib test web linux windows macos
          fi
          if [ ! -d "ios" ]; then
            flutter create .
            rm -rf lib test web linux windows macos
          fi

      - name: Build APK
        script: flutter build apk --release

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
