workflows:
  android-apk:
    name: HS Logistics — Android APK
    max_build_duration: 60
    instance_type: linux_x2
    environment:
      flutter: stable
    scripts:
      - name: Ensure Flutter project structure
        script: |
          if [ ! -f "pubspec.yaml" ]; then echo "❌ pubspec.yaml missing"; exit 1; fi
          if [ ! -d "android" ] || [ ! -d "ios" ]; then
            echo "⚙️ Generating missing platforms (android/ios/web)..."
            flutter create . --platforms=android,ios,web
          fi
      - name: Get dependencies
        script: flutter pub get
      - name: Build release APK
        script: flutter build apk --release
    artifacts:
      - build/**/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - info@hslogistics.pk
