name: hslogistics_app
description: HS Logistics mobile app (Payments + Bilty) via PHP API
publish_to: "none"
version: 1.1.1+3

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  intl: ^0.19.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
